-- Durable auth diagnostics for production incident analysis.
-- Stores token-safe event metadata from the Streamlit app.

create table if not exists public.auth_event_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  env text not null default 'unknown',
  event text not null,
  user_id uuid,
  sid uuid,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists idx_auth_event_logs_created_at_desc
  on public.auth_event_logs (created_at desc);

create index if not exists idx_auth_event_logs_event_created_at_desc
  on public.auth_event_logs (event, created_at desc);

create index if not exists idx_auth_event_logs_user_id_created_at_desc
  on public.auth_event_logs (user_id, created_at desc);

create index if not exists idx_auth_event_logs_sid_created_at_desc
  on public.auth_event_logs (sid, created_at desc);

alter table public.auth_event_logs enable row level security;

revoke all on table public.auth_event_logs from anon;
revoke all on table public.auth_event_logs from authenticated;

